#!/bin/sh -e

if [ -z "$( /usr/bin/which gmake )" ]
then
	MAKE=make
else
	MAKE=gmake
fi

unset BCD_MATH
cd gtk
${MAKE} cleaner
${MAKE} -e AUDIO_ALSA=1 BCD_MATH=0
${MAKE} clean
${MAKE} -e AUDIO_ALSA=1 BCD_MATH=1
${MAKE} clean
cd ..

UNAME_S=$( uname -s )

rm -rf Free42${UNAME_S}
mkdir Free42${UNAME_S}
cp gtk/README Free42${UNAME_S}
cp gtk/free42bin Free42${UNAME_S}
cp gtk/free42dec Free42${UNAME_S}
strip Free42${UNAME_S}/free42bin
strip Free42${UNAME_S}/free42dec
mkdir -p packages
tar cvfz packages/Free42${UNAME_S}.tgz Free42${UNAME_S}
rm -rf Free42${UNAME_S}
